[package]
name = "code-space"
version = "0.1.0"
edition = "2021"
default-run = "cs"

[[bin]]
name = "cs"
path = "src/main.rs"

[[bin]]
name = "app_pack"
path = "src/bin/app_pack.rs"

[[bin]]
name = "app_server"
path = "src/bin/app_server.rs"

[dependencies]
tokio = { version = "^1", features = ["full"] }
clap = { version = "^4", features = ["derive"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
json5 = "^0.4"
lazy_static = "^1.4.0"
regex = "^1"
rand = "^0.8"
env_logger = "^0.10"
log = "^0.4"
url = "^2.2"
actix-web = "^4"
actix-files = "^0.6"
deno_core = "^0.164"
swc = "^0.238"

[dev-dependencies]
mockall = "^0.11.2"
proptest = "^1"

[workspace]
members = [
    "packages/rsx-compiler",
    "packages/rsx-runtime",
    "packages/rsx-server"
]
