[package]
name = "code-space"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }

[dev-dependencies]

[workspace]
members = ["app_server", "app_client", "app_libs"]
