[package]
name = "code-space"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "^3", features = ["derive"] }
serde = { version = "^1", features = ["derive"] }
hyper = { version = "^0.14", features = ["full"] }
config = "^0.13"
serde_json = "^1"
itertools = "^0.10"
regex = "^1"
rand = "^0.8"
anyhow = "^1"
env_logger = "^0.9"
deno_core = "^0.151"
tracing = "^0.1"
tracing-subscriber = "^0.3"
lazy_static = "^1.4.0"
url = "^2.2"
utf8_slice = "^1"
json5 = "^0.4"
actix-web = "^4"
actix = "^0.13"
actix-files = "^0.6"
num_cpus = "1.0"
swc = "^0.227.10"

[dev-dependencies]
proptest = "^1"

[workspace]
members = ["crates/app-server", "crates/rust-wasm-web"]
