[package]
name = "code-space"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }

[dev-dependencies]

[workspace]
members = ["packages/rc-ref", "packages/reactive", "packages/str"]
