[package]
name = "code-space"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
itertools = "0.10.2"
regex = "1"
rand = "0.8.4"
anyhow = "1.0.57"
env_logger = "0.9.0"
deno_core = "0.143"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
proptest = "1.0.0"

[workspace]
members = ["app_server", "app_client", "app_libs"]
