[package]
name = "code-space"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "^3", features = ["derive"] }
serde = { version = "^1", features = ["derive"] }
hyper = { version = "^0.14", features = ["full"] }
config = "^0.13"
serde_json = "^1"
itertools = "^0.10"
regex = "^1"
rand = "^0.8"
anyhow = "^1"
env_logger = "^0.9"
deno_core = "^0.146.0"
tracing = "^0.1"
tracing-subscriber = "^0.3"
async-std="^1.12.0"
lazy_static="^1.4.0"
url= "^2.2"
utf8_slice = "^1"
json5="^0.4"

[dev-dependencies]
proptest = "^1"

[workspace]
members = [
    "crates/app-client",
    "crates/app-server",
    "crates/app-libs",
    "crates/rust-wasm-node",
    "crates/rust-wasm-web",
]
