[package]
authors = ["michaelbguo <michaelbguo@tencent.com>"]
edition = "2021"
name = "rsx-compiler"
version = "0.1.0"

[dependencies]
json5 = "^0.4"
lazy_static = "^1.4.0"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
swc = "0.251"
tokio = { version = "^1", features = ["full"] }
