[package]
name = "rsx-compiler"
version = "0.1.0"
edition = "2021"
authors = ["michaelbguo <michaelbguo@tencent.com>"]

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
json5 = "^0.4"
lazy_static = "^1.4.0"
swc = "^0.251"
