[package]
authors = ["michaelbguo <michaelbguo@tencent.com>"]
edition = "2021"
name = "rsx-runtime"
version = "0.1.0"

[dependencies]
deno_core = "^0.185"
lazy_static = "^1.4.0"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
tokio = { version = "^1", features = ["full"] }
