[package]
authors = ["michaelbguo <michaelbguo@tencent.com>"]
edition = "2021"
name = "rsx-server"
version = "0.1.0"

[dependencies]
actix = "^0.13.0"
actix-files = "^0.6"
actix-web = "^4"
actix-rt = "^2"
awc = { version = "^3.0.0", features = ["openssl"] }
openssl = "^0.10.40"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
