[package]
name = "rsx-server"
version = "0.1.0"
edition = "2021"
authors = ["michaelbguo <michaelbguo@tencent.com>"]

[dependencies]
tokio = { version = "^1", features = ["full"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
actix-web = "^4"
url = "^2.2"
actix-files = "0.6"
